### ISSUE TITLE
Really cool product -can we have a video?

### ISSUE THREAD

**Issue by Kirk3gaard** [dholab/SNAILS#1]
Hi 

This is a really cool idea. Any chance that you could post  a link to a video with the SNAILS in action? 

+ I seem unable to find the mention of the pipettor itself in the description and where to get it like the links you have for the motors etc.

Best regards 
Rasmus

**Comment by TrentPrall** [comment]
Hi Rasmus,

Thanks for reaching out to us. We have updated our GitHub repository to
include more information on parts and assembly. We are currently working on
an instructional video for assembly that will be online shortly. Below is a
complete parts list.

The design uses an Ovation M 10-100 ul Micropipette
https://vistalab.com/product/mechanical-volume-adjust/
Catalog # 1070-0100
If you have any questions or need assistance setting up an instrument
please feel free to ask.

Best,
Trent
O'Connor Lab
University of Wisconsin, Madison

**Comment by neuropathbasel** [comment]
Hi Trent,
Many thanks for the publication and this github page detailing your invention.
However, so far I am not really not sure I do understand the setup and how it is used for pipetting.
I would like to support Rasmus' request for a video of the SNAILS in action.
Many thanks & best wishes
Claus

**Comment by TrentPrall** [comment]
Hey @neuropathbasel and @Kirk3gaard,

Sorry for the delay but we have finally created assembly videos that are linked on the main page. Hopefully that helps you deploy if you're still interested in trying them out.
